name: Test FlowKit downstream (develop)

on:
  push:
    branches:
      - develop

jobs:
  test-develop:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout FlowIO
        uses: actions/checkout@v4
        with:
          ref: develop
          path: flowio

      - name: Checkout FlowKit (develop)
        uses: actions/checkout@v4
        with:
          repository: whitews/FlowKit
          ref: develop
          path: flowkit

      - name: Install FlowKit
        working-directory: flowkit
        run: |
          pip install --upgrade pip
          pip install .
          pip install ../flowio

      - name: Run FlowKit tests
        working-directory: flowkit
        run: |
          python3 ./run_tests.py
